import { db } from "@/lib/db";
import { marketplaceItems } from "@/lib/db/schema";

export const SEED_APPS = [
  // Mejoras (4 apps)
  {
    title: "Reportes Avanzados",
    subtitle: "Análisis y reportes personalizados",
    description: "Crea reportes personalizados con gráficos interactivos, filtros avanzados y exportación a múltiples formatos. Ideal para analizar datos en tiempo real.",
    category: "Mejoras",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/reports.svg",
    imageUrl: "/images/reports.png",
    features: [],
    tags: ["análisis", "reportes", "datos"],
  },
  {
    title: "Panel Personalizado",
    subtitle: "Dashboards a medida",
    description: "Diseña tu propio dashboard con widgets personalizables. Arrastra, suelta y configura el layout perfecto para tu equipo.",
    category: "Mejoras",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/dashboard.svg",
    imageUrl: "/images/dashboard.png",
    features: [],
    tags: ["dashboard", "personalización", "widgets"],
  },
  {
    title: "API Completa",
    subtitle: "Integración sin límites",
    description: "Acceso total a la API REST de WhatsaaS para integraciones avanzadas. Documentación completa y webhooks en tiempo real.",
    category: "Mejoras",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/api.svg",
    imageUrl: "/images/api.png",
    features: [],
    tags: ["api", "integraciones", "desarrollador"],
  },
  {
    title: "Integraciones Premium",
    subtitle: "Conecta con 100+ servicios",
    description: "Integración con Google Workspace, Salesforce, HubSpot, Stripe, y más. Sincronización bidireccional automática.",
    category: "Mejoras",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/integrations.svg",
    imageUrl: "/images/integrations.png",
    features: [],
    tags: ["integraciones", "terceros", "automatización"],
  },

  // Productividad (4 apps)
  {
    title: "Gestor de Tareas",
    subtitle: "Organiza tu trabajo",
    description: "Crea, asigna y monitorea tareas con diferentes prioridades. Kanban, lista y calendario. Colabora con tu equipo en tiempo real.",
    category: "Productividad",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/tasks.svg",
    imageUrl: "/images/tasks.png",
    features: [],
    tags: ["tareas", "productividad", "equipo"],
  },
  {
    title: "Gestión de Proyectos",
    subtitle: "Planifica y ejecuta proyectos",
    description: "Planificación de proyectos con timeline, dependencias, asignación de recursos. Seguimiento de progreso y reportes de Gantt.",
    category: "Productividad",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/projects.svg",
    imageUrl: "/images/projects.png",
    features: [],
    tags: ["proyectos", "gestión", "planificación"],
  },
  {
    title: "Gestor de Documentos",
    subtitle: "Colaboración en documentos",
    description: "Crea, edita y colabora en documentos en tiempo real. Control de versiones, comentarios y permisos granulares.",
    category: "Productividad",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/documents.svg",
    imageUrl: "/images/documents.png",
    features: [],
    tags: ["documentos", "colaboración", "almacenamiento"],
  },
  {
    title: "Control de Tiempo",
    subtitle: "Trackea tiempo de trabajo",
    description: "Monitoreo de horas trabajadas, proyectos y tareas. Reportes de productividad y facturación automática basada en horas.",
    category: "Productividad",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/timetracking.svg",
    imageUrl: "/images/timetracking.png",
    features: [],
    tags: ["tiempo", "productividad", "facturación"],
  },

  // Automatización (4 apps)
  {
    title: "Constructor de Workflows",
    subtitle: "Automatiza procesos",
    description: "Crea flujos de trabajo visuales sin código. Triggers, acciones condicionales y automatizaciones complejas.",
    category: "Automatización",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/workflows.svg",
    imageUrl: "/images/workflows.png",
    features: [],
    tags: ["automatización", "workflows", "procesos"],
  },
  {
    title: "Automatización de Emails",
    subtitle: "Campañas de email automatizadas",
    description: "Crea secuencias de email automáticas basadas en comportamiento. Segmentación, A/B testing y reportes detallados.",
    category: "Automatización",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/email-automation.svg",
    imageUrl: "/images/email-automation.png",
    features: [],
    tags: ["email", "marketing", "automatización"],
  },
  {
    title: "Webhooks Avanzados",
    subtitle: "Conecta en tiempo real",
    description: "Recibe eventos en tiempo real de tu aplicación. Webhooks seguros, reintentos automáticos y debugging.",
    category: "Automatización",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/webhooks.svg",
    imageUrl: "/images/webhooks.png",
    features: [],
    tags: ["webhooks", "integraciones", "tiempo real"],
  },
  {
    title: "Integración Zapier",
    subtitle: "Conecta con 5000+ apps",
    description: "Integración nativa con Zapier para conectar WhatsaaS con miles de aplicaciones sin código.",
    category: "Automatización",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/zapier.svg",
    imageUrl: "/images/zapier.png",
    features: [],
    tags: ["zapier", "integraciones", "automatización"],
  },

  // Nodos (4 apps)
  {
    title: "Nodo de Decisión",
    subtitle: "Lógica condicional en flujos",
    description: "Crea ramificaciones en tus flujos basadas en condiciones. IF/ELSE, switch y lógica compleja con interfaz visual.",
    category: "Nodos",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/decision-node.svg",
    imageUrl: "/images/decision-node.png",
    features: [],
    tags: ["nodos", "lógica", "flujos"],
  },
  {
    title: "Nodo de Base de Datos",
    subtitle: "Consulta y manipula datos",
    description: "Ejecuta queries SQL, inserta, actualiza y elimina datos. Soporte para múltiples bases de datos.",
    category: "Nodos",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/database-node.svg",
    imageUrl: "/images/database-node.png",
    features: [],
    tags: ["database", "datos", "sql"],
  },
  {
    title: "Nodo de API",
    subtitle: "Llamadas HTTP personalizadas",
    description: "Realiza peticiones HTTP a cualquier API externa. Headers, autenticación y transformación de respuestas.",
    category: "Nodos",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/api-node.svg",
    imageUrl: "/images/api-node.png",
    features: [],
    tags: ["api", "http", "integraciones"],
  },
  {
    title: "Nodo Personalizado",
    subtitle: "Desarrolla nodos con código",
    description: "Crea nodos personalizados con JavaScript/TypeScript. Librería de código reutilizable y marketplace de nodos.",
    category: "Nodos",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/custom-node.svg",
    imageUrl: "/images/custom-node.png",
    features: [],
    tags: ["nodos", "desarrollo", "código"],
  },

  // Apps (4 apps)
  {
    title: "Constructor de Formularios",
    subtitle: "Crea formularios sin código",
    description: "Drag & drop para crear formularios profesionales. Validaciones, campos personalizados y temas automáticos.",
    category: "Apps",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/forms.svg",
    imageUrl: "/images/forms.png",
    features: [],
    tags: ["formularios", "captura", "datos"],
  },
  {
    title: "Gestor de Encuestas",
    subtitle: "Crea y analiza encuestas",
    description: "Encuestas interactivas con lógica condicional. Análisis en tiempo real, exportación de resultados y reportes.",
    category: "Apps",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/surveys.svg",
    imageUrl: "/images/surveys.png",
    features: [],
    tags: ["encuestas", "feedback", "análisis"],
  },
  {
    title: "Constructor de Landing Pages",
    subtitle: "Páginas de conversión optimizadas",
    description: "Crea landing pages profesionales sin código. Templates optimizados, A/B testing y seguimiento de conversiones.",
    category: "Apps",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/landing-pages.svg",
    imageUrl: "/images/landing-pages.png",
    features: [],
    tags: ["landing pages", "conversión", "marketing"],
  },
  {
    title: "Tienda E-commerce",
    subtitle: "Vende productos en línea",
    description: "Catálogo de productos, carrito de compras, pagos seguros y gestión de inventario. Integraciones con Stripe y PayPal.",
    category: "Apps",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/ecommerce.svg",
    imageUrl: "/images/ecommerce.png",
    features: [],
    tags: ["ecommerce", "ventas", "tienda"],
  },

  // Marketing (4 apps)
  {
    title: "Email Marketing Pro",
    subtitle: "Campañas de email profesionales",
    description: "Crea campañas de email hermosas. Templates, segmentación avanzada, automatización y analítica detallada.",
    category: "Marketing",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/email-marketing.svg",
    imageUrl: "/images/email-marketing.png",
    features: [],
    tags: ["email", "marketing", "campañas"],
  },
  {
    title: "SMS Marketing",
    subtitle: "Mensajes SMS masivos",
    description: "Envía SMS a tus clientes. Segmentación, plantillas, seguimiento y cumplimiento GDPR.",
    category: "Marketing",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/sms-marketing.svg",
    imageUrl: "/images/sms-marketing.png",
    features: [],
    tags: ["sms", "marketing", "mensajes"],
  },
  {
    title: "Gestor de Redes Sociales",
    subtitle: "Publica en todas tus redes",
    description: "Programación de posts, análisis de engagement, calendar view. Conecta Instagram, Facebook, Twitter, LinkedIn.",
    category: "Marketing",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/social-media.svg",
    imageUrl: "/images/social-media.png",
    features: [],
    tags: ["redes sociales", "marketing", "social"],
  },
  {
    title: "Analítica Avanzada",
    subtitle: "Comprende el comportamiento",
    description: "Seguimiento avanzado de usuarios, eventos personalizados, análisis de cohortes y predictivos.",
    category: "Marketing",
    isDefault: false,
    isFunctional: false,
    appType: "installable" as const,
    iconUrl: "/icons/analytics.svg",
    imageUrl: "/images/analytics.png",
    features: [],
    tags: ["analítica", "datos", "comportamiento"],
  },
];

export async function seedApps() {
  try {
    // Primero, crear las apps de ejemplo
    for (const app of SEED_APPS) {
      await db.insert(marketplaceItems).values({
        title: app.title,
        subtitle: app.subtitle,
        description: app.description,
        category: app.category,
        isDefault: app.isDefault,
        isFunctional: app.isFunctional,
        appType: app.appType,
        iconUrl: app.iconUrl,
        imageUrl: app.imageUrl,
        features: app.features,
        tags: app.tags,
        status: "active",
      });
    }

    console.log("✅ Apps de ejemplo cargadas exitosamente");
    return true;
  } catch (error) {
    console.error("❌ Error cargando apps:", error);
    throw error;
  }
}

export async function seedDefaultApps() {
  try {
    // Crear Notas app por defecto
    await db.insert(marketplaceItems).values({
      title: "Notas",
      subtitle: "Toma notas rápidas",
      description:
        "Aplicación integrada para tomar notas rápidas. Sincroniza automáticamente entre dispositivos. Esta es una aplicación preinstalada que no puede ser desinstalada.",
      category: "Herramientas",
      isDefault: true,
      isFunctional: false,
      appType: "default",
      status: "active",
      features: [
        {
          id: "note-creation",
          name: "Creación de notas",
          description: "Crea notas sin límite",
        },
        {
          id: "note-sync",
          name: "Sincronización",
          description: "Sincronización en tiempo real",
        },
      ],
    });

    // Crear Calendario app por defecto
    await db.insert(marketplaceItems).values({
      title: "Calendario",
      subtitle: "Gestiona eventos y citas",
      description:
        "Calendario integrado para gestionar eventos, citas y reuniones. Sincronización con Google Calendar y Outlook. Esta es una aplicación preinstalada que no puede ser desinstalada.",
      category: "Herramientas",
      isDefault: true,
      isFunctional: false,
      appType: "default",
      status: "active",
      features: [
        {
          id: "event-creation",
          name: "Creación de eventos",
          description: "Crea eventos ilimitados",
        },
        {
          id: "calendar-sync",
          name: "Sincronización",
          description: "Sincronización con otros calendarios",
        },
        {
          id: "reminders",
          name: "Recordatorios",
          description: "Notificaciones de eventos próximos",
        },
      ],
    });

    console.log("✅ Apps por defecto cargadas exitosamente");
    return true;
  } catch (error) {
    console.error("❌ Error cargando apps por defecto:", error);
    throw error;
  }
}
